from pathlib import Path
import json


def read(path):
    return Path(path).read_text(encoding="utf-8")


def write(path, text):
    Path(path).write_text(text, encoding="utf-8")


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly 1 occurrence, found {count}")
    return text.replace(old, new, 1)


# 1) Make the i18n core deterministic: completion layer first, then navigation,
# and do not let init return while the presentation layer is still racing in.
core_path = "assets/i18n/core-v2.js"
core = read(core_path)
core = replace_once(
    core,
    '''        await loadUiScript("theme-manager.js?v=20260908-4", "BetInsightTheme");
        await loadUiScript("navigation-enhancements.js?v=20260909-3", "BetInsightNavigationEnhancements");
        await loadUiScript("i18n/member-completion.js?v=20260912-1", "BetInsightMemberCompletion");
        return true;''',
    '''        await loadUiScript("theme-manager.js?v=20260908-4", "BetInsightTheme");
        await loadUiScript("i18n/member-completion.js?v=20260913-1", "BetInsightMemberCompletion");
        await loadUiScript("navigation-enhancements.js?v=20260913-1", "BetInsightNavigationEnhancements");
        return true;''',
    "core enhancement order",
)
core = replace_once(
    core,
    '''        loadUiEnhancements();
        return language;''',
    '''        await loadUiEnhancements();
        return language;''',
    "core init await enhancements",
)
core = replace_once(
    core,
    '''        loadUiEnhancements();
        return defaultLanguage;''',
    '''        await loadUiEnhancements();
        return defaultLanguage;''',
    "core fallback await enhancements",
)
write(core_path, core)


# 2) Remove the observer storm in the member-wide completion layer.
# MutationObserver callbacks are asynchronous, so the previous `applying` flag alone
# did not suppress the mutation records generated by the translation pass itself.
completion_path = "assets/i18n/member-completion.js"
completion = read(completion_path)
completion = replace_once(
    completion,
    '''    } finally { applying=false; }
  }

  function startObserver() {''',
    '''    } finally {
      if (observer) observer.takeRecords();
      applying=false;
    }
  }

  function startObserver() {''',
    "member completion clear own walk records",
)
completion = replace_once(
    completion,
    '''    observer=new MutationObserver(records=>{
      if (applying) return;
      for (const record of records) {
        if (record.type === "characterData") processText(record.target);
        else if (record.type === "attributes") processAttr(record.target,record.attributeName);
        else record.addedNodes.forEach(node=>{
          if (node.nodeType === Node.TEXT_NODE) processText(node);
          else if (node.nodeType === Node.ELEMENT_NODE) walk(node);
        });
      }
    });''',
    '''    observer=new MutationObserver(records=>{
      if (applying) return;
      applying=true;
      try {
        for (const record of records) {
          if (record.type === "characterData") processText(record.target);
          else if (record.type === "attributes") processAttr(record.target,record.attributeName);
          else record.addedNodes.forEach(node=>{
            if (node.nodeType === Node.TEXT_NODE) processText(node);
            else if (node.nodeType === Node.ELEMENT_NODE) walk(node);
          });
        }
      } finally {
        observer.takeRecords();
        applying=false;
      }
    });''',
    "member completion guarded observer",
)
write(completion_path, completion)


# 3) The legacy dashboard adapter remains for safe routing and locale formatters,
# but it must not run a second full-DOM translator/observer when the new completion
# layer is present. This removes the second source of feedback loops.
dashboard_path = "assets/i18n/dashboard-legacy.js"
dashboard = read(dashboard_path)
dashboard = replace_once(
    dashboard,
    '''  function applyPseudoLabels() {
    let style = document.getElementById("bi-dashboard-language-style");
    if (!style) { style = document.createElement("style"); style.id = "bi-dashboard-language-style"; document.head.appendChild(style); }
    style.textContent = lang() === "en" ? `.private-row-hidden::after{content:"${t("privacyEmail",{},"Email protected")}"!important}.private-token-hidden::after{content:"${t("privacyAccess",{},"Personal access protected")}"!important}.private-value-hidden::after{content:"${t("privacyProtected",{},"Protected")}"!important}.membership-info-tier.current-tier::after{content:"${t("yourPlan",{},"YOUR PLAN")}"!important}` : "";
  }''',
    '''  function applyPseudoLabels() {
    let style = document.getElementById("bi-dashboard-language-style");
    if (!style) { style = document.createElement("style"); style.id = "bi-dashboard-language-style"; document.head.appendChild(style); }
    style.textContent = lang() !== "de" ? `.private-row-hidden::after{content:"${t("privacyEmail",{},"Protected")}"!important}.private-token-hidden::after{content:"${t("privacyAccess",{},"Protected")}"!important}.private-value-hidden::after{content:"${t("privacyProtected",{},"Protected")}"!important}.membership-info-tier.current-tier::after{content:"${t("yourPlan",{},"YOUR PLAN")}"!important}` : "";
  }''',
    "dashboard pseudo labels all languages",
)
dashboard = replace_once(
    dashboard,
    '''  async function boot() {
    installSafeRouting();
    await i18n()?.init?.();
    walk(document.body);
    const observer = new MutationObserver(records => {
      if (applying) return;
      for (const record of records) {
        if (record.type === "characterData") processText(record.target);
        else for (const node of record.addedNodes) node.nodeType===Node.TEXT_NODE ? processText(node) : (node instanceof Element && walk(node));
      }
    });
    observer.observe(document.body,{subtree:true,childList:true,characterData:true});
    window.addEventListener("bi:languagechange",()=>walk(document.body));
  }''',
    '''  async function boot() {
    installSafeRouting();
    await i18n()?.init?.();

    const refreshLocaleOnly = () => {
      applyLocaleFunctions();
      applyPseudoLabels();
      document.title = t("title", {}, "BetInsight Profil & Empfehlungscenter");
    };

    // The six-language member completion layer is now the single DOM translator.
    // Keep this legacy adapter for safe routing and number/date formatting only.
    if (window.BetInsightMemberCompletion) {
      refreshLocaleOnly();
      window.addEventListener("bi:languagechange", refreshLocaleOnly);
      return;
    }

    // Fallback for an unlikely completion-layer load failure.
    walk(document.body);
    const observer = new MutationObserver(records => {
      if (applying) return;
      for (const record of records) {
        if (record.type === "characterData") processText(record.target);
        else for (const node of record.addedNodes) node.nodeType===Node.TEXT_NODE ? processText(node) : (node instanceof Element && walk(node));
      }
    });
    observer.observe(document.body,{subtree:true,childList:true,characterData:true});
    window.addEventListener("bi:languagechange",()=>walk(document.body));
  }''',
    "dashboard single translator mode",
)
write(dashboard_path, dashboard)


# 4) Compatibility loader: cache-bust the fixed core and do not start the old
# dashboard-completion observer when the member-wide translator is available.
app_nav_path = "assets/app-navigation.js"
app_nav = read(app_nav_path)
app_nav = replace_once(
    app_nav,
    'await loadScript("i18n/core-v2.js","BetInsightI18n");',
    'await loadScript("i18n/core-v2.js?v=20260913-1","BetInsightI18n");',
    "app navigation core cache bust",
)
app_nav = replace_once(
    app_nav,
    '        await loadScript("i18n/dashboard-completion.js");',
    '        if (!window.BetInsightMemberCompletion) await loadScript("i18n/dashboard-completion.js");',
    "app navigation skip redundant dashboard completion",
)
write(app_nav_path, app_nav)


# 5) Navigation enhancement labels must update in all six languages instead of
# becoming permanently German after the first render.
nav_path = "assets/navigation-enhancements.js"
nav = read(nav_path)
nav = replace_once(
    nav,
    '''  const text = (de, en) => {
    try { return window.BetInsightI18n?.getLanguage?.() === "en" ? en : de; }
    catch (e) { return de; }
  };''',
    '''  const NAV_TEXT = Object.freeze({
    "Academy & Ressourcen": {en:"Academy & Resources",es:"Academy y recursos",pt:"Academy e recursos",it:"Academy e risorse",fr:"Academy et ressources"},
    "Werbematerial & Downloads": {en:"Marketing Material & Downloads",es:"Material promocional y descargas",pt:"Material de divulgação e downloads",it:"Materiale promozionale e download",fr:"Supports marketing et téléchargements"},
    "Sprache / Land": {en:"Language / Country",es:"Idioma / País",pt:"Idioma / País",it:"Lingua / Paese",fr:"Langue / Pays"}
  });
  const text = (de, en) => {
    try {
      const lang = String(window.BetInsightI18n?.getLanguage?.() || "de").toLowerCase().split("-")[0];
      if (lang === "de") return de;
      if (lang === "en") return en;
      return NAV_TEXT[de]?.[lang] || de;
    } catch (e) { return de; }
  };''',
    "navigation six-language text helper",
)
nav = replace_once(
    nav,
    '''  function enhanceResources(sidebar) {
    if (sidebar.querySelector('[data-bi-nav-group="resources-group"]')) return;
    const original = sidebar.querySelector('[data-bi-nav-route="ressourcen"]');''',
    '''  function enhanceResources(sidebar) {
    const existing = sidebar.querySelector('[data-bi-nav-group="resources-group"]');
    if (existing) {
      const groupLabel = existing.querySelector('.bi-nav-group-button .bi-nav-label');
      if (groupLabel) groupLabel.textContent = text("Academy & Ressourcen", "Academy & Resources");
      const academyLabel = existing.querySelector('[data-bi-enhancement-route="academy"] .bi-nav-label');
      if (academyLabel) academyLabel.textContent = "BetInsight Academy";
      const downloadsLabel = existing.querySelector('[data-bi-enhancement-route="werbematerial"] .bi-nav-label');
      if (downloadsLabel) downloadsLabel.textContent = text("Werbematerial & Downloads", "Marketing Material & Downloads");
      return;
    }
    const original = sidebar.querySelector('[data-bi-nav-route="ressourcen"]');''',
    "navigation refresh resources labels",
)
nav = replace_once(
    nav,
    '''      if (!language.dataset.biSettingsEnhanced) {
        language.dataset.biSettingsEnhanced = "1";
        const title = document.createElement("div");
        title.className = "bi-nav-settings-title bi-nav-language-title";
        title.innerHTML = `<span aria-hidden="true">🌍</span><span>${text("Sprache / Land", "Language / Country")}</span>`;
        language.prepend(title);
        language.classList.add("bi-language-settings-block");
      }
      if (language.parentElement !== footer) footer.prepend(language);''',
    '''      if (!language.dataset.biSettingsEnhanced) {
        language.dataset.biSettingsEnhanced = "1";
        const title = document.createElement("div");
        title.className = "bi-nav-settings-title bi-nav-language-title";
        title.innerHTML = `<span aria-hidden="true">🌍</span><span></span>`;
        language.prepend(title);
        language.classList.add("bi-language-settings-block");
      }
      const languageTitle = language.querySelector(".bi-nav-language-title span:last-child");
      if (languageTitle) languageTitle.textContent = text("Sprache / Land", "Language / Country");
      if (language.parentElement !== footer) footer.prepend(language);''',
    "navigation refresh language title",
)
write(nav_path, nav)


# 6) Cache-bust the compatibility loader on the live root dashboard.
index_path = "index.html"
index = read(index_path)
index = replace_once(
    index,
    'assets/app-navigation.js?v=20260906-resources-1',
    'assets/app-navigation.js?v=20260913-i18n-freeze-1',
    "root app navigation cache bust",
)
write(index_path, index)


# 7) Add the dynamic strings visible on the dashboard/account-history card to all
# six keyed dictionaries so the single translator also covers runtime content.
runtime = {
    "de": {
        "balanceUpdatedRuntime": "Kontostand wurde aktualisiert.",
        "premiumActiveRuntime": "Premium aktiv",
        "premiumPlusActiveRuntime": "Premium Plus aktiv",
        "runtimeSync": "Laufzeit wird mit Premium v1.2 synchronisiert.",
        "runtimeActiveSync": "Aktiv · Laufzeit wird mit Premium v1.2 synchronisiert",
        "accountMovements": "Kontobewegungen",
        "accountMovementsLazy": "Nur bei Bedarf laden – spart Make-Credits.",
        "displayOnly": "NUR ANZEIGE",
        "accountMovementsNotLoaded": "Kontobewegungen sind noch nicht geladen.",
        "loadAccountMovements": "Kontobewegungen laden",
        "showMore": "Weitere anzeigen",
        "noAutomaticMake": "Keine automatische Make-Abfrage beim Profilaufruf."
    },
    "en": {
        "balanceUpdatedRuntime": "Balance updated.",
        "premiumActiveRuntime": "Premium active",
        "premiumPlusActiveRuntime": "Premium Plus active",
        "runtimeSync": "Membership duration is being synchronized with Premium v1.2.",
        "runtimeActiveSync": "Active · membership duration is being synchronized with Premium v1.2",
        "accountMovements": "Account activity",
        "accountMovementsLazy": "Load only when needed — saves Make credits.",
        "displayOnly": "DISPLAY ONLY",
        "accountMovementsNotLoaded": "Account activity has not been loaded yet.",
        "loadAccountMovements": "Load account activity",
        "showMore": "Show more",
        "noAutomaticMake": "No automatic Make request when opening the profile."
    },
    "es": {
        "balanceUpdatedRuntime": "Saldo actualizado.",
        "premiumActiveRuntime": "Premium activo",
        "premiumPlusActiveRuntime": "Premium Plus activo",
        "runtimeSync": "La duración se está sincronizando con Premium v1.2.",
        "runtimeActiveSync": "Activo · la duración se está sincronizando con Premium v1.2",
        "accountMovements": "Movimientos de la cuenta",
        "accountMovementsLazy": "Cargar solo cuando sea necesario — ahorra créditos de Make.",
        "displayOnly": "SOLO VISUALIZACIÓN",
        "accountMovementsNotLoaded": "Los movimientos de la cuenta aún no se han cargado.",
        "loadAccountMovements": "Cargar movimientos",
        "showMore": "Mostrar más",
        "noAutomaticMake": "No se realiza ninguna consulta automática a Make al abrir el perfil."
    },
    "pt": {
        "balanceUpdatedRuntime": "Saldo atualizado.",
        "premiumActiveRuntime": "Premium ativo",
        "premiumPlusActiveRuntime": "Premium Plus ativo",
        "runtimeSync": "A duração está sendo sincronizada com o Premium v1.2.",
        "runtimeActiveSync": "Ativo · a duração está sendo sincronizada com o Premium v1.2",
        "accountMovements": "Movimentações da conta",
        "accountMovementsLazy": "Carregue somente quando necessário — economiza créditos do Make.",
        "displayOnly": "SOMENTE EXIBIÇÃO",
        "accountMovementsNotLoaded": "As movimentações da conta ainda não foram carregadas.",
        "loadAccountMovements": "Carregar movimentações",
        "showMore": "Mostrar mais",
        "noAutomaticMake": "Nenhuma consulta automática ao Make ao abrir o perfil."
    },
    "it": {
        "balanceUpdatedRuntime": "Saldo aggiornato.",
        "premiumActiveRuntime": "Premium attivo",
        "premiumPlusActiveRuntime": "Premium Plus attivo",
        "runtimeSync": "La durata viene sincronizzata con Premium v1.2.",
        "runtimeActiveSync": "Attivo · la durata viene sincronizzata con Premium v1.2",
        "accountMovements": "Movimenti del conto",
        "accountMovementsLazy": "Carica solo quando serve — risparmia crediti Make.",
        "displayOnly": "SOLO VISUALIZZAZIONE",
        "accountMovementsNotLoaded": "I movimenti del conto non sono ancora stati caricati.",
        "loadAccountMovements": "Carica movimenti",
        "showMore": "Mostra altro",
        "noAutomaticMake": "Nessuna richiesta automatica a Make all'apertura del profilo."
    },
    "fr": {
        "balanceUpdatedRuntime": "Solde mis à jour.",
        "premiumActiveRuntime": "Premium actif",
        "premiumPlusActiveRuntime": "Premium Plus actif",
        "runtimeSync": "La durée est en cours de synchronisation avec Premium v1.2.",
        "runtimeActiveSync": "Actif · la durée est en cours de synchronisation avec Premium v1.2",
        "accountMovements": "Mouvements du compte",
        "accountMovementsLazy": "Chargez uniquement si nécessaire — économise des crédits Make.",
        "displayOnly": "AFFICHAGE UNIQUEMENT",
        "accountMovementsNotLoaded": "Les mouvements du compte ne sont pas encore chargés.",
        "loadAccountMovements": "Charger les mouvements",
        "showMore": "Afficher plus",
        "noAutomaticMake": "Aucune requête Make automatique à l'ouverture du profil."
    }
}

for language, additions in runtime.items():
    path = Path(f"assets/i18n/pages/dashboard/{language}.json")
    data = json.loads(path.read_text(encoding="utf-8"))
    page = data.setdefault("dashboardPage", {})
    page.update(additions)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("i18n freeze and runtime translation patch applied successfully.")
