(()=>{
'use strict';
const API='https://lszlaglwlixejzytrurg.supabase.co/functions/v1/betinsight-football-admin';
const SESSION_KEY='betinsight_admin_session_v1';
const SPECIAL={
  '__BI_INTL_FRIENDLY__':{kind:'api',leagueId:10,label:'Freundschaftsspiel · Nationalmannschaften',manualType:'Freundschaftsspiel Nationalmannschaften',manualCompetition:'Internationales Freundschaftsspiel'},
  '__BI_INTL_QUALIFICATION__':{kind:'qualification',label:'Qualifikation · Nationalmannschaften',manualType:'Qualifikation',manualCompetition:'Qualifikation'},
  '__BI_INTL_NATIONS__':{kind:'api',leagueId:5,label:'UEFA Nations League',manualType:'Länderspiel',manualCompetition:'UEFA Nations League'},
  '__BI_INTL_OTHER__':{kind:'manual',label:'Länderspiel / Sonstiges',manualType:'Länderspiel',manualCompetition:'Länderspiel'}
};
const clean=v=>String(v||'').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let fixtures=[],mode=null,panel=null;

const codes=('AD AE AF AG AI AL AM AO AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BR BS BT BW BY BZ CA CD CF CG CH CI CK CL CM CN CO CR CU CV CW CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET FI FJ FM FO FR GA GB GD GE GH GI GM GN GQ GR GT GW GY HK HN HR HT HU ID IE IL IN IQ IR IS IT JM JO JP KE KG KH KI KM KN KP KR KW KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MR MT MU MV MW MX MY MZ NA NE NG NI NL NO NP NR NU NZ OM PA PE PG PH PK PL PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SI SK SL SM SN SO SR SS ST SV SY SZ TD TG TH TJ TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VN VU WS YE ZA ZM ZW').split(' ');
const deDN=typeof Intl.DisplayNames==='function'?new Intl.DisplayNames(['de'],{type:'region'}):null;
const enDN=typeof Intl.DisplayNames==='function'?new Intl.DisplayNames(['en'],{type:'region'}):null;
const countries=[...new Set(codes.map(c=>deDN?deDN.of(c):c).filter(Boolean).concat(['England','Schottland','Wales','Nordirland','Kosovo']))].sort((a,b)=>a.localeCompare(b,'de'));
const e2d=new Map();
codes.forEach(c=>{const en=enDN?enDN.of(c):'',de=deDN?deDN.of(c):'';if(en&&de)e2d.set(norm(en),de)});
[['Republic of Ireland','Irland'],['Czech Republic','Tschechien'],['Czechia','Tschechien'],['Turkey','Türkei'],['Türkiye','Türkei'],['North Macedonia','Nordmazedonien'],['Faroe Islands','Färöer'],['United States','USA'],['South Korea','Südkorea'],['Korea Republic','Südkorea'],['Ivory Coast','Elfenbeinküste'],['Cape Verde','Kap Verde']].forEach(([a,b])=>e2d.set(norm(a),b));
const german=name=>e2d.get(norm(name))||clean(name);

function token(){try{const s=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'{}');return clean(s.token)}catch(e){return''}}
async function sessionHash(){const t=token();if(!t)throw new Error('Admin-Sitzung fehlt.');const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('')}
async function api(payload){
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',credentials:'omit',body:JSON.stringify({...payload,session_hash:await sessionHash()})});
  const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch(e){}
  if(!r.ok||d.ok!==true)throw new Error(d.message||d.error||('API-Fehler '+r.status));return d;
}
function berlinDate(add=0){const d=new Date(Date.now()+add*86400000),p=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return o.year+'-'+o.month+'-'+o.day}
function season(){return Number(berlinDate().slice(0,4))}
function parts(iso){const d=new Date(iso),dp=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(x=>[x.type,x.value])),tp=Object.fromEntries(new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d).map(x=>[x.type,x.value]));return{date:dp.year+'-'+dp.month+'-'+dp.day,time:tp.hour+':'+tp.minute}}
function display(iso){try{return new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}catch(e){return iso}}
function status(msg,type=''){const el=document.getElementById('biIntlStatus');if(!el)return;el.textContent=msg;el.style.color=type==='error'?'#ff9da3':type==='ok'?'#7dffb2':'#ffcf75'}
function specialUi(on){const m=document.getElementById('biManualGameWrap');if(m)m.style.display=on?'none':'';const b=document.getElementById('lookupBtn');if(b)b.style.display=on?'none':'';if(on){const s=document.getElementById('leagueStatus');if(s){s.textContent='';s.className='status'}}}
function countriesList(){if(document.getElementById('biIntlCountries'))return;const d=document.createElement('datalist');d.id='biIntlCountries';d.innerHTML=countries.map(n=>'<option value="'+n.replace(/&/g,'&amp;').replace(/"/g,'&quot;')+'"></option>').join('');document.body.appendChild(d)}
function clearTop(){const h=document.getElementById('homeTeam'),a=document.getElementById('awayTeam'),d=document.getElementById('spielDatum'),t=document.getElementById('anpfiff');if(h){h.innerHTML='<option value="">Spiel oben auswählen</option>';h.disabled=true}if(a){a.innerHTML='<option value="">Spiel oben auswählen</option>';a.disabled=true}if(d)d.value='';if(t)t.value='';const c=document.getElementById('confirmedEvent');if(c)c.classList.add('hidden');const mf=document.getElementById('marketFieldset');if(mf)mf.disabled=true}

function mount(){
 if((panel=document.getElementById('biIntlTopPanel')))return;
 const home=document.getElementById('homeTeam'),cell=home&&home.closest('div'),grid=cell&&cell.parentElement;if(!grid)return;
 countriesList();panel=document.createElement('div');panel.id='biIntlTopPanel';panel.style.cssText='display:none;grid-column:1/-1;margin:2px 0 8px;padding:16px;border:1px solid rgba(0,218,255,.38);border-radius:15px;background:rgba(4,31,44,.72)';
 panel.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:12px"><div><strong style="font-size:16px">🌍 Nationalmannschaften</strong><div style="font-size:12px;color:#9fc7d8;margin-top:4px">Spiele werden direkt hier oben geladen.</div></div><button id="biIntlReset" type="button" style="border:1px solid rgba(0,218,255,.35);background:transparent;color:#d8eef8;border-radius:999px;padding:9px 14px;font-weight:800;cursor:pointer">Andere Liga / Wettbewerb</button></div>'+
 '<div id="biIntlCompWrap" style="display:none;margin-bottom:12px"><label style="display:block;margin-bottom:6px;font-weight:800">Qualifikations-Wettbewerb</label><select id="biIntlComp"><option>Wird geladen …</option></select></div>'+
 '<div id="biIntlFixtureWrap" style="display:none"><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px"><div><label style="display:block;margin-bottom:6px;font-weight:800">Mannschaft suchen</label><input id="biIntlSearch" placeholder="z. B. Italien oder Frankreich"></div><div><label style="display:block;margin-bottom:6px;font-weight:800">Spiel auswählen</label><select id="biIntlFixture"><option>Spiele werden geladen …</option></select></div></div><button id="biIntlManualToggle" type="button" style="margin-top:10px;border:0;background:transparent;color:#8fdcff;text-decoration:underline;cursor:pointer;padding:4px 0">Spiel nicht dabei? Hier oben manuell eintragen</button></div>'+
 '<div id="biIntlManual" style="display:none"><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px"><div><label style="display:block;margin-bottom:6px;font-weight:800">Wettbewerb / Bezeichnung *</label><input id="biIntlMComp"></div><div><label style="display:block;margin-bottom:6px;font-weight:800">Heimteam / Land *</label><input id="biIntlMHome" list="biIntlCountries" placeholder="z. B. Deutschland"></div><div><label style="display:block;margin-bottom:6px;font-weight:800">Auswärtsteam / Land *</label><input id="biIntlMAway" list="biIntlCountries" placeholder="z. B. Frankreich"></div><div><label style="display:block;margin-bottom:6px;font-weight:800">Spieldatum *</label><input id="biIntlMDate" type="date"></div><div><label style="display:block;margin-bottom:6px;font-weight:800">Anpfiff (Deutschland) *</label><input id="biIntlMTime" type="time"></div><div style="display:flex;align-items:end"><button id="biIntlMApply" type="button" style="width:100%;padding:12px 16px;border:0;border-radius:999px;background:#16a8f5;color:#fff;font-weight:900;cursor:pointer">✓ Spiel übernehmen</button></div></div></div>'+
 '<div id="biIntlStatus" style="min-height:18px;margin-top:10px;font-size:13px;color:#ffcf75"></div>';
 grid.insertBefore(panel,cell);
 document.getElementById('biIntlSearch').addEventListener('input',render);
 document.getElementById('biIntlFixture').addEventListener('change',()=>{const f=fixtures.find(x=>String(x.fixture_id)===clean(document.getElementById('biIntlFixture').value));if(f)useFixture(f)});
 document.getElementById('biIntlComp').addEventListener('change',async()=>{const s=document.getElementById('biIntlComp'),id=Number(s.value||0);if(id)await loadFixtures(id,clean(s.options[s.selectedIndex].textContent))});
 document.getElementById('biIntlManualToggle').addEventListener('click',showManual);
 document.getElementById('biIntlMApply').addEventListener('click',useManual);
 document.getElementById('biIntlReset').addEventListener('click',()=>{if(typeof window.__biClearManualEvent==='function')window.__biClearManualEvent();fixtures=[];mode=null;panel.style.display='none';specialUi(false);const l=document.getElementById('liga');if(l){l.disabled=false;l.value='';l.focus()}});
}
function render(){const s=document.getElementById('biIntlFixture'),q=norm(document.getElementById('biIntlSearch').value),rows=fixtures.filter(f=>!q||[f.home_team,f.away_team,german(f.home_team),german(f.away_team),f.league_name].map(norm).join(' ').includes(q));s.innerHTML='<option value="">Bitte Spiel auswählen</option>'+rows.map(f=>'<option value="'+f.fixture_id+'">'+(display(f.date)+' · '+german(f.home_team)+' – '+german(f.away_team)).replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</option>').join('');if(!rows.length)s.innerHTML='<option value="">Kein passendes Spiel gefunden</option>'}
function showManual(){document.getElementById('biIntlFixtureWrap').style.display='none';document.getElementById('biIntlCompWrap').style.display='none';document.getElementById('biIntlManual').style.display='';const c=document.getElementById('biIntlMComp');if(c&&!c.value)c.value=mode?.manualCompetition||'Länderspiel';status('Spiel hier oben manuell ergänzen.')}
async function loadFixtures(id,name){document.getElementById('biIntlFixtureWrap').style.display='';document.getElementById('biIntlManual').style.display='none';document.getElementById('biIntlSearch').value='';document.getElementById('biIntlFixture').innerHTML='<option>Spiele werden geladen …</option>';status('Aktuelle Spiele werden aus API-Football geladen …');try{const d=await api({action:'fixtures',league_id:id,season:season(),from:berlinDate(),to:berlinDate(100)});fixtures=Array.isArray(d.fixtures)?d.fixtures:[];render();if(fixtures.length)status(fixtures.length+' kommende Spiele geladen · API-Football','ok');else{status('Aktuell kein Spiel in der API. Manuelle Eingabe ist hier oben möglich.','error');showManual();document.getElementById('biIntlMComp').value=name||mode?.manualCompetition||''}}catch(e){status((e.message||'API konnte nicht geladen werden')+' · Manuelle Eingabe ist möglich.','error');showManual()}}
async function loadQual(){document.getElementById('biIntlCompWrap').style.display='';document.getElementById('biIntlFixtureWrap').style.display='none';document.getElementById('biIntlManual').style.display='none';const s=document.getElementById('biIntlComp');s.innerHTML='<option>Qualifikationen werden geladen …</option>';status('Qualifikations-Wettbewerbe werden geladen …');try{const d=await api({action:'leagues_search',search:'Qualification',season:season()}),ls=(Array.isArray(d.leagues)?d.leagues:[]).filter(x=>/qualif/i.test(clean(x.name)));s.innerHTML='<option value="">Bitte Qualifikation auswählen</option>'+ls.map(x=>'<option value="'+x.league_id+'">'+(clean(x.name)+(x.country?' · '+clean(x.country):'')).replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</option>').join('');if(ls.length)status(ls.length+' Qualifikations-Wettbewerbe gefunden.','ok');else{status('Keine Qualifikation in der API gefunden. Manuelle Eingabe ist möglich.','error');showManual()}}catch(e){status((e.message||'Qualifikationen konnten nicht geladen werden')+' · Manuelle Eingabe ist möglich.','error');showManual()}}
function useFixture(f){const p=parts(f.date),meta={spielart:mode?.manualType||'Länderspiel',wettbewerb:clean(f.league_name)||mode?.label||'Länderspiel',home_team:german(f.home_team),away_team:german(f.away_team),spiel_datum:p.date,anpfiff:p.time,manual_event_id:'API-FOOTBALL-'+f.fixture_id,event_source:'API_FOOTBALL',api_event_id:String(f.fixture_id),api_commence_time:clean(f.date),sport_key:'API_FOOTBALL'};if(typeof window.__biUseManualEvent!=='function'){status('Spiel konnte nicht übernommen werden.','error');return}window.__biUseManualEvent(meta);panel.style.display='';specialUi(true);const c=document.getElementById('confirmedEvent');if(c)c.innerHTML='✓ API-Spiel bestätigt: <strong>'+german(f.home_team)+' – '+german(f.away_team)+'</strong><br>'+clean(f.league_name)+' · '+display(f.date);status('✓ '+german(f.home_team)+' – '+german(f.away_team)+' übernommen · API-Football','ok')}
function useManual(){const comp=clean(document.getElementById('biIntlMComp').value),home=clean(document.getElementById('biIntlMHome').value),away=clean(document.getElementById('biIntlMAway').value),date=clean(document.getElementById('biIntlMDate').value),time=clean(document.getElementById('biIntlMTime').value);if(!comp||!home||!away||!date||!time){status('Bitte alle Pflichtfelder ausfüllen.','error');return}if(norm(home)===norm(away)){status('Heim- und Auswärtsteam dürfen nicht identisch sein.','error');return}const meta={spielart:mode?.manualType||'Länderspiel',wettbewerb:comp,home_team:home,away_team:away,spiel_datum:date,anpfiff:time,manual_event_id:'BI-MANUAL-'+Date.now(),event_source:'MANUAL',sport_key:'MANUAL'};if(typeof window.__biUseManualEvent!=='function'){status('Spiel konnte nicht übernommen werden.','error');return}window.__biUseManualEvent(meta);panel.style.display='';specialUi(true);status('✓ Manuelles Länderspiel übernommen.','ok')}
async function activate(v){mount();mode=SPECIAL[v];if(!mode||!panel)return;clearTop();specialUi(true);panel.style.display='';document.getElementById('biIntlCompWrap').style.display='none';document.getElementById('biIntlFixtureWrap').style.display='none';document.getElementById('biIntlManual').style.display='none';document.getElementById('biIntlMComp').value=mode.manualCompetition||'';status('');if(mode.kind==='manual')return showManual();if(mode.kind==='qualification')return loadQual();return loadFixtures(mode.leagueId,mode.label)}
function bind(){mount();const l=document.getElementById('liga');if(!l)return;if(!l.dataset.biIntlV18){l.dataset.biIntlV18='1';l.addEventListener('change',e=>{const v=clean(l.value);if(!SPECIAL[v]){if(panel)panel.style.display='none';specialUi(false);return}e.stopImmediatePropagation();activate(v)},true)}if(SPECIAL[clean(l.value)])specialUi(true)}
const boot=()=>{bind();new MutationObserver(bind).observe(document.body,{childList:true,subtree:true})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();